export { default as WikiPage } from "./wiki/WikiPage.js";
export { default as TagList } from "./tags/TagList.js";
export { default as Register } from "./register/register.js";
export { default as Login } from "./login/login.js";
export { default as Home } from "./home/home.js";
export { default as Forum } from "./forum/forum.js";
export { default as EditWiki } from "./EditWiki/EditWiki.js";
export { default as EditHistory } from "./EditHistory/EditHistory.js";
export { default as SearchWiki } from "./SearchWiki/SearchWiki.js";
